name: workopia
services:
    db:
        container_name: workopiaDB
        image: postgres:16.6
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db-data:/var/lib/postgresql/data
